net-dmz.pdf: net-dmz.tex header.tex net-dmz.jpg
	pdflatex -jobname=net-dmz net-dmz
	pdflatex -jobname=net-dmz net-dmz

clean:
	rm -fr auto
	rm -f net-dmz.aux net-dmz.log net-dmz.pdf net-dmz.dvi net-dmz.out
